I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    image pencil = ("pencil.png", 0.8)
Exception: Not a displayable: (u'pencil.png', 0.8)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    image pencil = ("pencil.png", 0.8)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\ast.py", line 1015, in execute
    renpy.exports.image(self.imgname, img)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\exports.py", line 374, in image
    d = renpy.easy.displayable(d)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\easy.py", line 136, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: (u'pencil.png', 0.8)

Windows-8-6.2.9200
Ren'Py 7.3.2.320
The Good, The Bad and the Mutant 1.0
Fri Jul 19 00:02:34 2019
