I'm sorry, but an uncaught exception occurred.

Executing ATL code at game/script.rpy:33
  File "game/script.rpy", line 30, in script
    show fam_mutate with dissolve:
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    show fam_mutate with dissolve:
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\ast.py", line 1181, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\ast.py", line 1151, in show_imspec
    atl=atl)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\exports.py", line 717, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\display\core.py", line 1078, in add
    thing._show()
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\display\transform.py", line 1048, in _show
    super(ATLTransform, self)._show()
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\display\transform.py", line 1014, in _show
    self.update_state()
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\display\transform.py", line 1036, in update_state
    fr = self.execute(self, self.st, self.at)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\atl.py", line 564, in execute
    action, arg, pause = block.execute(trans, timebase, self.atl_state, events)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\atl.py", line 771, in execute
    action, arg, pause = stmt.execute(trans, target - start, child_state, events)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\atl.py", line 1230, in execute
    value = interpolate(complete, old, new, PROPERTIES[k])
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\atl.py", line 176, in interpolate
    return correct_type(a + t * (b - a), b, type)
  File "C:\Users\Heidi Chan\Documents\renpy-7.3.2-sdk\renpy\atl.py", line 149, in correct_type
    return ty(v)
TypeError: 'tuple' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Babs Project 1.0
Thu Jul 18 21:58:40 2019
